<?php
/**
 * unit-testcase:/unit/database/action.phtml
 *
 * @creation  2019-03-04
 * @version   1.0
 * @package   unit-testcase
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-03-04
 */
namespace OP;

/* @var $app     UNIT\App  */
/* @var $form    UNIT\Form */
/* @var $prod    string    */
/* @var $action  string    */
/* @var $io      boolean   */

//	...
include('action_menu.phtml');

//	...
