<?php
/**
 * module-testcase:/unit/database/orm/form.phtml
 *
 * @created   2019-04-19
 * @version   1.0
 * @package   module-testcase
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @creation  2019-04-19
 */
namespace OP;

/* @var $record \OP\UNIT\ORM\Record */

//  Generate "Form" object.
$form = $record->Form();

//	...
$form->Validate();

//	...
$disabled = $record->isFound() ? '':'disabled';
?>
<section>
	<?php $form->Start() ?>
	<table>
		<tr>
			<td>ai</td>
			<td><?php $form->Input('ai') ?></td>
		</tr>
		<?php foreach(['ai','required','number','select','checkbox','radio'] as $input_name): ?>
		<tr>
			<td><?php $form->Label($input_name) ?></td>
			<td><?php $form->Input($input_name) ?></td>
			<td><?php $form->Error($input_name) ?></td>
		</tr>
		<?php endforeach; ?>
		<tr>
			<td>timestamp</td>
			<td><?php $form->Value('timestamp') ?></td>
		</tr>
		<tr>
			<td colspan=3 style="text-align:center;">
				<button name="save"> Save </button>
			</td>
		</tr>
		<tr>
			<td colspan=3 style="text-align:center;">
				<input type="submit" name="delete" value=" Delete " <?= $disabled ?> />
			</td>
		</tr>
	</table>
	<?php $form->Finish() ?>
</section>
