<?php
/**
 * module-testcase:/unit/database/orm/menu.phtml
 *
 * @created   2019-04-19
 * @version   1.0
 * @package   module-testcase
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-04-19
 */
namespace OP;

?>
<section>
	|
	<a href="?selftest=1" >Selftest</a> |
	<a href="?" >Create</a> |
	<a href="?form=1" >Form</a> |
</section>
